routes/classes.py
from flask import Flask,Blueprint,request,redirect,url_for,render_template,session,flash
from models.models import Users,Schools,Student_Eval,Classes,Subjects,Profs,QuestionsTrack,db
from utils.graphs import make_graph 
from sqlalchemy import func

classes_bp=Blueprint('classes',__name__)



@classes_bp.route("/classes")
def classes():
    if 'school_username' and 'school_name' in session:
        classes=Classes.query.join(Classes.schools).filter(Schools.name==session['school_name']).all()
        return render_template("classes.html",classes=classes)
    else:
        return redirect(url_for("home.home"))
    
@classes_bp.route('/edit_classe/<int:id>',methods=['POST','GET'])
def edit_classe(id):
    if 'school_username' and 'school_name' in session:
        classe=Classes.query.get(id)
        classes=Classes.query.join(Classes.schools).join(Schools.user).filter(Users.username==session['school_username']).all()
        if classe in classes:
            if request.method=="POST":
                name=request.form.get("nom").strip()
                classe.name=name
                db.session.commit()
                flash("Class updated successfully.", "success")
                return redirect(url_for('classes.classes'))  
            else:
                return render_template("edit_classe.html",classe=classe)    
        else:
            return render_template("error_page.html")
    else:
        return redirect(url_for("home.home"))

@classes_bp.route('/delete_classe/<int:id>')
def delete_classe(id):
    if 'school_username' and 'school_name' in session:
        classe=Classes.query.get(id)
        classes=Classes.query.join(Classes.schools).filter(Schools.name==session['school_name']).all()
        if classe in classes:
            for student in classe.students:
                student.classe_id=None
                db.session.flush()
            Classes.query.filter_by(id=id).delete()
            db.session.commit()
            flash("Class deleted deleted.", "success")
            return redirect(url_for('classes.classes'))
        else:
            return render_template("error_page.html")
    else:
        return redirect(url_for("home.home"))
    
@classes_bp.route('/add_classe',methods=['POST','GET'])
def add_classe():
        if request.method=="POST":
            school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()
            name=request.form.get("nom").strip()
            class_exist=Classes.query.join(Classes.schools).join(Schools.user).filter((Users.username==session['school_username'])&(func.lower(Classes.name)==name.lower())).first()
            if class_exist:
                flash("Class already exist.", "failed")
                return redirect(url_for('classes.classes'))
            new_classe=Classes(name=name,students_nbrs=0,school_id=school.id)
            db.session.add(new_classe)
            db.session.commit()
            db.session.close()
            flash("Class added successfully.", "success")
            return redirect(url_for('classes.classes'))

@classes_bp.route('/start_eval/<int:id>')
def start_eval(id):
    if 'school_username' and 'school_name' in session:
        classe=Classes.query.get(id)
        if classe.eval==0:
            classe.eval=1
            db.session.flush()
            for student in classe.students:
                new_student_eval=Student_Eval(student_id=student.id)
                db.session.add(new_student_eval)
        elif classe.eval==1:
            classe.eval=0
            db.session.flush()
            for student in classe.students:
                Student_Eval.query.filter_by(student_id=student.id).delete()
                db.session.flush()

        db.session.commit()
        return redirect(url_for('classes.classes'))
    else:
        return redirect(url_for("home.home"))

@classes_bp.route('/rapport/<int:id>')
def rapport(id):
    if 'school_username' and 'school_name' in session:
        classe=Classes.query.filter_by(id=id).first()
        return render_template("subjects_rapport.html",classe=classe,qt=QuestionsTrack)
    else:
        return redirect(url_for("home.home"))
    
@classes_bp.route('/rapport/<int:classe_id>/<int:subject_id>/<int:prof_id>')
def rapport_details(classe_id,subject_id,prof_id):
    if 'school_username' and 'school_name' in session:
        prof=Profs.query.get(prof_id)  
        classe=Classes.query.get(classe_id)
        subject=Subjects.query.get(subject_id)
        qt=QuestionsTrack.query.filter((QuestionsTrack.classe_id==classe_id)&(QuestionsTrack.subject_id==subject_id)&(QuestionsTrack.prof_id==prof_id))
        valeurs_q1=[qt.filter(QuestionsTrack.q1==1).count()
                    ,qt.filter(QuestionsTrack.q1==2).count()
                    ,qt.filter(QuestionsTrack.q1==3).count()
                    ,qt.filter(QuestionsTrack.q1==4).count()
                    ,qt.filter(QuestionsTrack.q1==5).count()]
        make_graph(valeurs_q1,1,subject_id,classe_id)
        valeurs_q2=[qt.filter(QuestionsTrack.q2==1).count()
                    ,qt.filter(QuestionsTrack.q2==2).count()
                    ,qt.filter(QuestionsTrack.q2==3).count()
                    ,qt.filter(QuestionsTrack.q2==4).count()
                    ,qt.filter(QuestionsTrack.q2==5).count()]
        make_graph(valeurs_q2,2,subject_id,classe_id)
        valeurs_q3=[qt.filter(QuestionsTrack.q3==1).count()
                    ,qt.filter(QuestionsTrack.q3==2).count()
                    ,qt.filter(QuestionsTrack.q3==3).count()
                    ,qt.filter(QuestionsTrack.q3==4).count()
                    ,qt.filter(QuestionsTrack.q3==5).count()]
        make_graph(valeurs_q3,3,subject_id,classe_id)
        valeurs_q4=[qt.filter(QuestionsTrack.q4==1).count()
                    ,qt.filter(QuestionsTrack.q4==2).count()
                    ,qt.filter(QuestionsTrack.q4==3).count()
                    ,qt.filter(QuestionsTrack.q4==4).count()
                    ,qt.filter(QuestionsTrack.q4==5).count()]
        make_graph(valeurs_q4,4,subject_id,classe_id)
        c1=qt.all()
        c2=qt.all()
        return render_template("rapport.html",c1=c1,c2=c2,classe=classe,subject=subject,classe_id=str(classe_id),subject_id=str(subject_id),prof=prof)
    else:
        return redirect(url_for("home.home"))
    
@classes_bp.route('/rapport/<int:classe_id>/<int:subject_id>/profs')
def more_than_prof(classe_id,subject_id):
    if 'school_username' and 'school_name' in session:
        subject=Subjects.query.get(subject_id)
        classe=Classes.query.get(classe_id)
        profs=subject.profs
        return render_template('more_than_prof.html',profs=profs,qt=QuestionsTrack,classe=classe,subject=subject)
    else:
        return redirect(url_for("home.home"))

routes/dashboard.py
from flask import Blueprint,redirect,url_for,render_template,session
from models.models import Schools,Students,Classes,Subjects,Profs,db
dashboard_bp=Blueprint('dashboard',__name__)

@dashboard_bp.route('/dashboard')
def dashboard():
    if 'school_username' and 'school_name' in session:
        students=Students.query.join(Students.classes).join(Classes.schools).filter(Schools.name==session['school_name']).all()
        classes=Classes.query.join(Classes.schools).filter(Schools.name==session['school_name']).all()
        profs=Profs.query.join(Profs.schools).filter(Schools.name==session['school_name']).all()
        subjects=Subjects.query.join(Subjects.classes).join(Classes.schools).filter(Schools.name==session['school_name']).all()
        return render_template("dashboard.html",students=students,classes=classes,profs=profs,subjects=subjects)
    else:
        return redirect(url_for("home.home"))
    

routes/profs.py
from flask import Blueprint,request,redirect,url_for,render_template,session,flash
from models.models import Users,Schools,Profs,db
profs_bp=Blueprint('profs',__name__)

@profs_bp.route("/profs")
def profs():
    if 'school_username' and 'school_name' in session:
        profs=Profs.query.join(Profs.schools).join(Schools.user).filter(Users.username==session['school_username']).all()
        return render_template("profs.html",profs=profs)
    else:
        return redirect(url_for("home.home"))

@profs_bp.route("/edit_prof/<int:id>",methods=['POST','GET'])
def edit_prof(id):
        if 'school_username' and 'school_name' in session:
            school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()
            prof=Profs.query.get(id)
            if prof in school.profs:
                if request.method=="POST":
                        lname=request.form.get("nom").strip()
                        fname=request.form.get("prenom").strip()
                        prof.fname=fname
                        prof.lname=lname
                        db.session.commit()
                        flash("Prof updated successfully.", "success")
                        return redirect(url_for('profs.profs'))
                else:
                        return render_template("edit_prof.html",prof=prof)
            else:
                return render_template("error_page.html")
        else:
            return redirect(url_for("home.home")) 

@profs_bp.route('/delete_prof/<int:id>')
def delete_prof(id):
    if 'school_username' and 'school_name' in session:
        school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()
        prof=Profs.query.get(id)
        if prof in school.profs:
            Profs.query.filter_by(id=id).delete()
            db.session.commit()
            flash("Prof deleted successfully.", "success")
            return redirect(url_for('profs.profs'))
        else:
            return render_template("error_page.html")
    else:
        return redirect(url_for("home.home"))
    
@profs_bp.route('/add_prof',methods=['POST','GET'])
def add_prof():
    if 'school_username' and 'school_name' in session:
        if request.method=="POST":
            lname=request.form.get("nom").strip()
            fname=request.form.get("prenom").strip()
            immatriculation=request.form.get("immatriculation").strip()
            already_exist=Profs.query.join(Profs.schools).join(Schools.user).filter(Users.username==session['school_username'],Profs.immatriculation==immatriculation).first()
            if already_exist:
                flash("Prof / immaatriculation already exist.", "failed")
                return redirect(url_for('profs.profs'))
            new_prof=Profs(fname=fname,lname=lname,immatriculation=immatriculation)
            db.session.add(new_prof)
            school=Schools.query.join(Schools.user).filter(and_(Users.username==session["school_username"],Schools.name==session['school_name'])).first()
            school.profs.append(new_prof)
            db.session.commit()
            flash("Prof added successfully.", "success")
        return redirect(url_for('profs.profs'))
    else:
        return redirect(url_for("home.home"))

routes/subjects.py
from flask import Blueprint,request,redirect,url_for,render_template,session,flash
from models.models import Users,Schools,Classes,Subjects,Profs,db
from sqlalchemy import func

subjects_bp=Blueprint('subjects',__name__)

    

@subjects_bp.route("/subjects")
def subjects():
    if 'school_username' and 'school_name' in session:
        school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()
        subjects=Subjects.query.filter_by(school_id=school.id).all()
        classes=Classes.query.join(Classes.schools).filter(Schools.name==session['school_name']).all()
        profs=Profs.query.join(Profs.schools).filter(Schools.name==session['school_name']).all()
        return render_template("subjects.html",subjects=subjects,classes=classes,profs=profs)
    else:
        return redirect(url_for("home.home"))
      
@subjects_bp.route("/edit_subject/<int:id>",methods=['POST','GET'])
def edit_subject(id):
    if 'school_username' and 'school_name' in session:
        school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()
        subject=Subjects.query.get(id)
        subjects=Subjects.query.filter_by(school_id=school.id).all()
        all_school_classes=Classes.query.join(Classes.schools).join(Schools.user).filter(Users.username==session['school_username']).all()
        all_school_profs=Profs.query.join(Profs.schools).join(Schools.user).filter(Users.username==session['school_username']).all()
        if subject in subjects: 
            if request.method=="POST":
                name=request.form.get("nom")
                form_classes=request.form.get("selectedClasses")
                form_profs=request.form.get("selectedProfs")
                if name:
                    subject.name=name 
                id_classes=[]
                id_profs=[]
                for i in form_classes:
                    if i.isdigit():
                        id_classes.append(int(i))
                for i in form_profs:
                    if i.isdigit():
                        id_profs.append(int(i))
                classes=Classes.query.filter(Classes.id.in_(id_classes)).all()
                subject.classes=classes
                profs=Profs.query.filter(Profs.id.in_(id_profs)).all()
                subject.profs=profs
                db.session.commit()
                flash("Subject updated successfully.", "success")
                return redirect(url_for('subjects.subjects'))
            else:   
                classes=Classes.query.join(Classes.schools).join(Schools.user).filter(Users.username==session['school_username']).all()
                profs=Profs.query.join(Profs.schools).join(Schools.user).filter(Users.username==session['school_username']).all()
                selected_classes=[{'id':classe.id,'name':classe.name} for classe in subject.classes if classe in all_school_classes]
                selected_profs=[{'id':prof.id,'name':prof.fname+" "+prof.lname} for prof in subject.profs if prof in all_school_profs]
                return render_template("edit_subject.html",subject=subject,classes=classes,profs=profs,selected_classes=selected_classes,selected_profs=selected_profs)
        else:
                return render_template("error_page.html")

    else:
            return redirect(url_for("home.home")) 
    
@subjects_bp.route('/delete_subject/<int:id>')
def delete_subject(id):
    if 'school_username' and 'school_name' in session:
        school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()
        subject=Subjects.query.get(id)
        subjects=Subjects.query.filter_by(school_id=school.id).all()
        if subject in subjects:
            Subjects.query.filter_by(id=id).delete()
            db.session.commit()
            flash("Subject deleted successfully.", "success")
            return redirect(url_for('subjects.subjects'))
        else:
            return render_template("error_page.html")
    else:
        return redirect(url_for("home.home"))


@subjects_bp.route('/add_subject', methods=['POST', 'GET'])
def add_subject():
    if 'school_username' in session and 'school_name' in session:
        school=Schools.query.join(Schools.user).filter(Users.username==session['school_username']).first()   
        if request.method == 'POST':
            name = request.form.get("name", "").strip()
            form_classes = request.form.get("selectedClasses", "")
            form_profs = request.form.get("selectedProfs", "")
            id_classes = [int(i.strip()) for i in form_classes.strip("[]").split(",") if i.strip().isdigit()]
            id_profs = [int(i.strip()) for i in form_profs.strip("[]").split(",") if i.strip().isdigit()]
            if name:
                subject_exist=Subjects.query.join(Subjects.classes).join(Classes.schools).join(Schools.user).filter(
                    (func.lower(Subjects.name)==name.lower())&(Users.username==session['school_username'])
                ).first()
                if subject_exist:
                    for prof_id in id_profs:
                        prof=Profs.query.get(prof_id)
                        if prof in subject_exist.profs:
                            id_profs.remove(prof_id)
                    for classe_id in id_classes:
                        classe=Classes.query.get(classe_id)
                        if classe in subject_exist.classes:
                            id_classes.remove(classe_id)
                    if not id_profs and not id_classes:
                        flash("Subject already exist.", "failed")
                        return redirect(url_for('subjects.subjects'))
                    if not id_classes:
                        for prof_id in id_profs:
                            prof=Profs.query.get(prof_id)
                            subject_exist.profs.append(prof)
                            db.session.commit()  
                        flash("Subject added successfully.", "success")
                        return redirect(url_for('subjects.subjects'))
                        
                classes = Classes.query.filter(Classes.id.in_(id_classes)).all() if id_classes else []
                profs = Profs.query.filter(Profs.id.in_(id_profs)).all() if id_profs else []
                new_subject = Subjects(name=name, profs=profs, classes=classes,school_id=school.id)
                db.session.add(new_subject)
                db.session.commit()
                flash("Subject added successfully.", "success")
                
            else:
                flash("Please fill in all required fields.", "failed")
            return redirect(url_for('subjects.subjects'))
    else:
        return redirect(url_for("home.home"))

templates/classes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modal.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/notifications.css') }}">
    <script src="https://kit.fontawesome.com/5b085c63cb.js" crossorigin="anonymous"></script>
    <title>Evaluation</title>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png">
</head>

<body>
{% include 'notifications.html' %}



    <div class="container">
         <aside>
            <div class="toggle">
                <img src="{{url_for('static',filename='images/logo.png')}}">
                <div class="logo">
                     <h2><span class="danger">   </span></h2>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">close</span>
                </div>
            </div>

            <div class="sidebar">
                <a href="{{url_for('dashboard.dashboard')}}" >
                    <span class="material-icons-sharp">dashboard</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('students.students')}}">
                    <span class="material-icons-sharp">person_outline</span>
                    <h3>Etudiant</h3>
                </a>
                <a href="{{url_for('profs.profs')}}">
                    <i class="fa-sharp-duotone fa-solid fa-person-chalkboard" style="font-size: 19px;"></i>
                    <h3>Profs</h3>
                </a>
                <a href="{{url_for('subjects.subjects')}}">
                    <span class="material-symbols-outlined">subject</span>
                    <h3>Matieres</h3>
                </a>
                <a href="{{url_for('classes.classes')}}" class="active">
                    <span class="material-symbols-outlined">school</span>
                    <h3>Classes</h3>
                </a>
                <a href="{{url_for('auth.settings')}}">
                    <span class="material-icons-sharp">settings</span>
                    <h3>Settings</h3>
                </a>
                <a href="{{url_for('auth.logout')}}">
                    <span class="material-icons-sharp">logout</span>
                    <h3>Logout</h3>
                </a>
            </div>
        </aside>

        <main>
            <br><br>
            <h1>Analytiques</h1>
            <div class="analyse">
                <div class="sales">
                    <div class="status">
                        <div class="info">
                            <h3>Classes</h3>
                            <h1>{{classes|length}}</h1>
                        </div>
                    </div>
                </div>
            </div>

            <div class="new-users">
                <h2>Dernières Classes Ajoutées</h2>
                <div class="user-list">
                    {% for classe in classes[:3] %}
                    <div class="user">
                        <img src="{{ url_for('static', filename='images/classes.png') }}">
                        <h2>{{classe.name}}</h2>
                        <p>{{classe.students|length}}</p>
                    </div>
                    {%endfor%}
                    <button id="openModalBtn">
                        <img src="{{ url_for('static', filename='images/plus.png') }}">
                        <h2>Ajouter</h2>
                        <p>Plus de Classes</p>
                    </button>
                </div>
            </div>

            <div class="recent-orders">
                <h2>Liste des Classes</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Nombre d'Étudiants</th>
                            <th></th><th></th><th></th>
                        </tr>
                    </thead>
                    <tbody id="demandesList">
                        {%for classe in classes%}
                        <tr>
                            <th>{{classe.name}}</th>
                            <th>{{classe.students|length}}</th>
                            <th><a href="{{url_for('classes.edit_classe',id=classe.id)}}"><button class="reset">Modifier</button></a></th>
                            <th><a href="{{url_for('classes.delete_classe',id=classe.id)}}"><button class="reset">Supprimer</button></a></th>
                            <th><a href="{{url_for('classes.start_eval',id=classe.id)}}"><button class="reset">
                                {%if classe.eval == 0 %}
                                Commencer Evaluation
                                {%else%}
                                    Arrêter Evaluation
                                {%endif%}
                            
                            </button></a></th>
                            <th><a href="{{url_for('classes.rapport',id=classe.id)}}"><button class="reset">Rapport</button></a></th>

                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>

            <div class="button_container">
                <button id="showMoreBtn">Découvrir Plus</button>
            </div>
        </main>

        <div class="right-section">
            <div class="nav">
                <button id="menu-btn">
                    <span class="material-icons-sharp">menu</span>
                </button>
                <div class="dark-mode">
                    <span class="material-icons-sharp active">light_mode</span>
                    <span class="material-icons-sharp">dark_mode</span>
                </div>
            <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{session['school_username']}}</b></p>
                        <small class="text-muted">Admin</small>
                    </div>
                    <div class="profile-photo">
                        <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210180014/profile-removebg-preview.png">
                    </div>
                </div>
            </div>

            <div class="user-profile">
                <div class="logo">
                    <h2>{{session['school_name']}}</h2>
                    <p>Classes</p>
                </div>
            </div>
        </div>
    </div>

    <div id="myModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <h3>Ajouter une seule Classe</h3>
            <form id="singleStudentForm" action="{{url_for('classes.add_classe')}}" method="post">
                <label for="nom">Nom:</label>
                <input type="text" id="nom" name="nom" required>

                <button type="submit" class="btn-primary">Ajouter la Classe</button>
            </form>

            <hr>

        
        </div>
    </div>

    <script defer src="{{ url_for('static', filename='js/notifications.js') }}"></script>
    <script defer src="{{ url_for('static', filename='js/modal.js') }}"></script>
    <script src="{{ url_for('static', filename='js/show_more.js') }}"></script>
    <script src="{{ url_for('static', filename='js/orders.js') }}"></script>
    <script src="{{ url_for('static', filename='js/index.js') }}"></script>
</body>
</html>

templates/subjects_rapport.html
<!DOCTYPE html>
<html lang="en">

<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Sharp" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}">
    <script src="https://kit.fontawesome.com/5b085c63cb.js" crossorigin="anonymous"></script>
    <title>Evaluation</title>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.png') }}" type="image/png">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/modal.css') }}">
    
</head>

<body>
    <div class="container">
        <aside>
            <div class="toggle">
                <img src="{{url_for('static',filename='images/logo.png')}}">
                <div class="logo">
                     <h2><span class="danger">   </span></h2>
                </div>
                <div class="close" id="close-btn">
                    <span class="material-icons-sharp">close</span>
                </div>
            </div>

            <div class="sidebar">
                <a href="{{url_for('dashboard.dashboard')}}">
                    <span class="material-icons-sharp">dashboard</span>
                    <h3>Dashboard</h3>
                </a>
                <a href="{{url_for('students.students')}}">
                    <span class="material-icons-sharp">person_outline</span>
                    <h3>Etudiant</h3>
                </a>
                <a href="{{url_for('profs.profs')}}">
                    <i class="fa-sharp-duotone fa-solid fa-person-chalkboard" style="font-size: 19px;"></i>
                    <h3>Profs</h3>
                </a>
                <a href="{{url_for('subjects.subjects')}}" >
                    <span class="material-symbols-outlined">subject</span>
                    <h3>Matieres</h3>
                </a>
                <a href="{{url_for('classes.classes')}}" class="active">
                    <span class="material-symbols-outlined">school</span>
                    <h3>Classes</h3>
                </a>
                <a href="{{url_for('auth.settings')}}">
                    <span class="material-icons-sharp">settings</span>
                    <h3>Settings</h3>
                </a>
                <a href="{{url_for('auth.logout')}}">
                    <span class="material-icons-sharp">logout</span>
                    <h3>Logout</h3>
                </a>
            </div>
        </aside>

        <main>
            


            <div class="recent-orders">
                <h2>Liste des Matiéres</h2>
                <table>
                    <thead>
                        <tr>
                            <th>Nom</th>
                            <th>Participants à l’évaluation</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody id="demandesList">
                    {% for subject in classe.subjects%}
                        <tr>
                            <th>{{subject.name}}</th>
                            <th>{{qt.query.filter_by(subject_id=subject.id,classe_id=classe.id).count()}}</th>
                            {% if (qt.query.filter_by(subject_id=subject.id,classe_id=classe.id).count())>0 %}
                                {%if subject.profs|length>1 %}
                                <th><a href="{{url_for('classes.more_than_prof',classe_id=classe.id,subject_id=subject.id)}}"><button class="reset" >Rapport</button></a></th>
                                {%else%}
                                <th><a href="{{url_for('classes.rapport_details',classe_id=classe.id,subject_id=subject.id,prof_id=subject.profs[0].id)}}"><button class="reset">Rapport</button></a></th>
                                
                                {%endif%}

                            {%else%}
                                <th><button class="reset" >Rapport Indisponible</button></th>
                                
                            
                            {%endif%}
                        </tr>
                        {%endfor%}
                    </tbody>
                </table>
            </div>
        </main>

        <div class="right-section">
            <div class="nav">
                <button id="menu-btn">
                    <span class="material-icons-sharp">menu</span>
                </button>
                <div class="dark-mode">
                    <span class="material-icons-sharp active">light_mode</span>
                    <span class="material-icons-sharp">dark_mode</span>
                </div>
              <div class="profile">
                    <div class="info">
                        <p>Hey, <b>{{session['school_username']}}</b></p>
                        <small class="text-muted">Admin</small>
                    </div>
                    <div class="profile-photo">
                        <img src="https://media.geeksforgeeks.org/wp-content/uploads/20221210180014/profile-removebg-preview.png">
                    </div>
                </div>
            </div>

            <div class="user-profile">
                <div class="logo">
                    <h2>{{session['school_name']}}</h2>
                    <p>Tableau De Bord</p>
                </div>
            </div>
        </div>
    </div>



    <script defer src="{{url_for('static',filename='js/show_more.js')}}"></script>
    <script defer src="{{url_for('static',filename='js/orders.js')}}"></script>
    <script defer src="{{url_for('static',filename='js/modal.js')}}"></script>
    <script defer src="{{url_for('static',filename='js/index.js')}}"></script>
</body>

</html>